### ISSUE TITLE
A required class was missing while executing org.codehaus.mojo:jaxb2-maven-plugin:2.3:xjc: com/sun/codemodel/CodeWriter

### ISSUE THREAD

**Issue by MisooB** [JelmenGuhlke/jSEPA#1]
I cloned the repository and tried running mvn clean install, but I'm getting this error.
Already tried deleting .m2 apache repository.

[ERROR] Failed to execute goal org.codehaus.mojo:jaxb2-maven-plugin:2.3:xjc (xjc-eu.rbecker.jsepa.directdebit.xml.schema.pain_008_001_02) on project jSepa: Execution xjc-eu.rbecker.jsepa.directdebit.xml.schema.pain_008_001_02 of goal org.codehaus.mojo:jaxb2-maven-plugin:2.3:xjc failed: A required class was missing while executing org.codehaus.mojo:jaxb2-maven-plugin:2.3:xjc: com/sun/codemodel/CodeWriter
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.codehaus.mojo:jaxb2-maven-plugin:2.3
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/Michal-aardwark/.m2/repository/org/codehaus/mojo/jaxb2-maven-plugin/2.3/jaxb2-maven-plugin-2.3.jar
[ERROR] urls[1] = file:/C:/Users/Michal-aardwark/.m2/repository/javax/xml/bind/jaxb-api/2.2.11/jaxb-api-2.2.11.jar
[ERROR] urls[2] = file:/C:/Users/Michal-aardwark/.m2/repository/org/glassfish/jaxb/jaxb-core/2.2.11/jaxb-core-2.2.11.jar
[ERROR] urls[3] = file:/C:/Users/Michal-aardwark/.m2/repository/org/glassfish/jaxb/jaxb-runtime/2.2.11/jaxb-runtime-2.2.11.jar
[ERROR] urls[4] = file:/C:/Users/Michal-aardwark/.m2/repository/org/glassfish/jaxb/jaxb-xjc/2.2.11/jaxb-xjc-2.2.11.jar
[ERROR] urls[5] = file:/C:/Users/Michal-aardwark/.m2/repository/org/glassfish/jaxb/jaxb-jxc/2.2.11/jaxb-jxc-2.2.11.jar
[ERROR] urls[6] = file:/C:/Users/Michal-aardwark/.m2/repository/com/thoughtworks/qdox/qdox/2.0-M3/qdox-2.0-M3.jar
[ERROR] urls[7] = file:/C:/Users/Michal-aardwark/.m2/repository/org/sonatype/sisu/sisu-inject-bean/2.3.0/sisu-inject-bean-2.3.0.jar
[ERROR] urls[8] = file:/C:/Users/Michal-aardwark/.m2/repository/org/sonatype/sisu/sisu-guice/3.1.0/sisu-guice-3.1.0-no_aop.jar
[ERROR] urls[9] = file:/C:/Users/Michal-aardwark/.m2/repository/org/sonatype/sisu/sisu-guava/0.9.9/sisu-guava-0.9.9.jar
[ERROR] urls[10] = file:/C:/Users/Michal-aardwark/.m2/repository/org/sonatype/aether/aether-util/1.13.1/aether-util-1.13.1.jar
[ERROR] urls[11] = file:/C:/Users/Michal-aardwark/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar
[ERROR] urls[12] = file:/C:/Users/Michal-aardwark/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[13] = file:/C:/Users/Michal-aardwark/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[14] = file:/C:/Users/Michal-aardwark/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[15] = file:/C:/Users/Michal-aardwark/.m2/repository/org/codehaus/plexus/plexus-compiler-api/2.5/plexus-compiler-api-2.5.jar
[ERROR] urls[16] = file:/C:/Users/Michal-aardwark/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.22/plexus-utils-3.0.22.jar
[ERROR] urls[17] = file:/C:/Users/Michal-aardwark/.m2/repository/org/sonatype/plexus/plexus-build-api/0.0.7/plexus-build-api-0.0.7.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------: com.sun.codemodel.CodeWriter

Any advices?

**Comment by roben** [comment]
It looks like your maven is broken. Or maybe it just doesn't work with windows - I have never tested that. Could you try it on a Linux machine?

**Comment by cleemansen** [comment]
Same for me on a mac os machine.

Bumping the version for `jaxb2-maven-plugin` to the latest one (currently `2.5.0`) solves this for me.

**Comment by faisalshah42** [comment]
> Same for me on a mac os machine.
> 
> Bumping the version for `jaxb2-maven-plugin` to the latest one (currently `2.5.0`) solves this for me.

do I have to change it in pom.xml ?
